#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source=['basic.cpp'],
            target='basic',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])

bld.program(features='cxx',
            source=['add_loss.cpp'],
            target='add_loss',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])

bld.program(features='cxx',
            source=['turn_systematic_off.cpp'],
            target='turn_systematic_off',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])

bld.program(features='cxx',
            source=['seed_codes.cpp'],
            target='seed_codes',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])

bld.program(features='cxx',
            source=['recoding.cpp'],
            target='recoding',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])

bld.program(features='cxx',
            source=['add_layer.cpp'],
            target='add_layer',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])
