#! /usr/bin/env python
# encoding: utf-8

bld.program(features = 'cxx',
            source   = 'use_trace_layers.cpp',
            target   = 'use_trace_layers',
            use      = ['kodo_includes', 'boost_includes',
                        'fifi_includes', 'sak_includes'])
