#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='sliding_window.cpp',
            target='sliding_window',
            use=['kodo_includes', 'boost_includes',
                 'fifi_includes', 'sak_includes'])
