#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='customize_partitioning_scheme.cpp',
            target='customize_partitioning_scheme',
            use=['kodo_includes', 'boost_includes', 'fifi_includes',
                 'sak_includes'])
