#! /usr/bin/env python
# encoding: utf-8

# Note that this file is not needed for building the example with make

bld.program(features = 'cxx',
            source   = 'main.cpp',
            target   = 'sample_makefile',
            use      = ['kodo_includes', 'boost_includes',
                        'fifi_includes', 'sak_includes'])

